spring:
  application:
    name: gestion
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_limpieza
    username: mokeal_user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

jwt:
  secret: 5omo5MOKEALyvamo54tuc4s44l1mp14r
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG

mokeal:
  empresa:
    nombre: Mokeal
    nif: "60227433R"
    direccion: "C/ Ricardo Ortiz 44, 2ºB 28017 Madrid"
    telefono: "692120209"
    email: "mokeal.limpieza@gmail.com"
    cuentaBancaria: "ES57 2100 4991 6122 0025 7293"